"""empty message

Revision ID: 188e6874b3a4
Revises: ddf1908692a6
Create Date: 2023-07-26 11:45:47.754392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188e6874b3a4'
down_revision = 'ddf1908692a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.String(length=128), nullable=False))
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
